window.talentPics = {  
  "pressurized-glands": "Pressurized Glands",
  "survival-instincts": "Survival Instincts",
  "regenerative-microbes": "Regenerative Microbes",
  "envenomed-nest": "Envenomed Nest",
  "prolific-dispersal": "Prolific Dispersal",
  "ballistospores": "Ballistospores",
  "sustained-carapace": "Sustained Carapace",
  "adrenal-overload": "Adrenal Overload",
  "needlespine": "Needlespine",
  "vile-nest": "Vile Nest",
  "networked-carapace": "Networked Carapace",
  "calldown-mule": "Calldown: MULE",
  "adrenaline-boost": "Adrenaline Boost",
  "assault-strain": "Assault Strain",
  "bombard-strain": "Bombard Strain",
  "envenomed-spikes": "Envenomed Spikes",
  "evolutionary-link": "Evolutionary Link",
  "evolution-complete": "Evolution Complete",
  "evolve-monstrosity": "Evolve Monstrosity",
  "hivemind": "Hivemind",
  "locust-brood": "Locust Brood",
  "locust-nest": "Locust Nest",
  "soma-transference": "Soma Transference",
  "spatial-efficiency": "Spatial Efficiency",
  "ultimate-evolution": "Ultimate Evolution",
  "volatile-mutation": "Voltaile Mutation",
  "assault-scarab": "Assault Scarab",
  "bed-of-barbs": "Bed of Barbs",
  "beetle-juiced": "Beetle Juiced",
  "blood-for-blood": "Blood for Blood",
  "burning-rage": "Burning Rage",
  "chitinous-plating": "Chitinous Plating",
  "cocoon": "Cocoon",
  "cryptweave": "Cryptweave",
  "epicenter": "Epicenter",
  "extended-spikes": "Extended Spikes",
  "hardened-shield": "Hardened Shield",
  "hive-master": "Hive Master",
  "imposing-presence": "Imposing Presence",
  "leeching-scarabs": "Leeching Scarabs",
  "legion-of-beetles": "Legion of Beetles",
  "locust-needles": "Locust Needles",
  "locust-swarm": "Locust Swarm",
  "mercenary-lord": "Mercenary Lord",
  "persistent-carapace": "Persistent Carapace",
  "regeneration-master": "Regeneration Master",
  "rewind": "Rewind",
  "shed-exoskeleton": "Shed Exoskeleton",
  "spell-shield": "Spell Shield",
  "symbiotic-armor": "Symbiotic Armor",
  "underking": "Underking",
  "urticating-spines": "Urticating Spines",
  "amateur-opponent": "Amateur Opponent",
  "chrono-surge": "Chrono Surge",
  "follow-through": "Follow Through",
  "graviton-vortex": "Graviton Vortex",
  "khaydarian-resonance": "Khaydarian Resonance",
  "lethal-alacrity": "Lethal Alacrity",
  "nexus-blades": "Nexus Blades",
  "orbital-bombardment": "Orbital Bombardment",
  "phase-bulwark": "Phase Bulwark",
  "psionic-synergy": "Psionic Synergy",
  "psionic-wound": "Psionic Wound",
  "purifier-beam": "Purifier Beam",
  "reactive-parry": "Reactive Parry",
  "seasoned-marksman": "Seasoned Marksman",
  "shield-battery": "Shield Battery",
  "shield-surge": "Shield Surge",
  "solarite-reaper": "Solarite Reaper",
  "suppression-pulse": "Suppression Pulse",
  "target-purified": "Target Purified",
  "templar-s-zeal": "Templar's Zeal",
  "titan-killer": "Titan Killer",
  "triple-strike": "Triple Strike",
  "warp-sickness": "Warp Sickness",
  "zealot-charge": "Zealot Charge",
  "force-of-will": "Force of Will",
  "absolute-zero": "Absolute Zero",
  "army-of-the-dead": "Army of the Dead",
  "biting-cold": "Biting Cold",
  "block": "Block",
  "death-touch": "Death Touch",
  "destruction": "Desctruction",
  "embrace-death": "Embrace Death",
  "eternal-hunger": "Eternal Hunger",
  "frostmourne-feeds": "Frostmourne Feeds",
  "frost-presence": "Frost Presence",
  "frost-strike": "Frost Strike",
  "frozen-wastes": "Frozen Wastes",
  "immortal-coil": "Immortal Coil",
  "legion-of-northrend": "Legion of Northrend",
  "obliterate": "Obliterate",
  "relentless": "Relentless",
  "rune-tap": "Rune Tap",
  "stoneskin": "Stoneskin",
  "summon-sindragosa": "Summon Sindragosa",
  "trail-of-frost": "Trail of Frost",
  "army-of-hell": "Army of Hell",
  "battleborn": "Battleborn",
  "black-pool": "Black Pool",
  "bolt-of-the-storm": "Bolt of the Storm",
  "bound-minion": "Bound Minion",
  "bribe": "Bribe",
  "demonic-invasion": "Demonic Invasion",
  "demonic-smite": "Demonic-Smite",
  "fifth-circle": "Fifth Circle",
  "forced-recruitment": "Forced Recruitment",
  "gluttonous-ward": "Gluttonous Ward",
  "gluttony": "Gluttony",
  "hedonism": "Hedonism",
  "hellforged-armor": "Hellforged Armor",
  "infernal-globe": "Infernal Globe",
  "infused-power": "Infused Power",
  "march-of-sin": "March of Sin",
  "master-of-destruction": "Master of Desctruction",
  "perishing-flame": "Perishing Flame",
  "sieging-wrath": "Sieging Wrath",
  "sin-s-grasp": "Sin's Grasp",
  "taste-for-blood": "Taste for Blood",
  "arcane-barrage": "Arcane Barrage",
  "arcane-precision": "Arcane Precision",
  "blink-heal": "Blink Heal",
  "bouncy-dust": "Bouncy Dust",
  "cleanse": "Cleanse",
  "continuous-winds": "Continuous Winds",
  "critterize": "Critterize",
  "double-wyrmhole": "Double Wyrmhole",
  "dream-shot": "Dream Shot",
  "emerald-wind": "Emerald Wind",
  "greater-polymorph": "Greater Polymorph",
  "hardened-focus": "Hardened Focus",
  "hyper-shift": "Hyper Shift",
  "ice-block": "Ice Block",
  "manic-pixie": "Manic Pixie",
  "mistified": "Mistified",
  "peekaboo": "Peekaboo!",
  "phase-shield": "Phase Shield",
  "pixie-boost": "Pixie Boost",
  "revitalizing-mist": "Revitalizing Mist",
  "shield-dust": "Shield Dust",
  "sticky-flare": "Sticky Flare",
  "storm-shield": "Storm Shield",
  "unfurling-spray": "Unfurling Spray",
  "unstable-anomaly": "Unstable Anomaly",
  "a-card-to-play": "A Card to Play",
  "berserk": "Berserk",
  "bullseye": "Bullseye",
  "cluster-round": "Cluster Round",
  "confident-aim": "Confident Aim",
  "double-barreled": "Double-Barreled",
  "dusk-wings": "Dusk Wings",
  "executioner": "Executioner",
  "fight-or-flight": "Fight or Flight",
  "focused-attack": "Focused Attack",
  "giant-killer": "Giant Killer",
  "give-me-more": "Give Me More!",
  "hamstring-shot": "Hamstring Shot",
  "hyperion": "Hyperion",
  "nexus-frenzy": "Nexus Frenzy",
  "puttin-on-a-clinic": "Puttin' On a Clinic",
  "raiders-recruitment": "Raiders' \"Recruitment\"",
  "raynor-s-raiders": "Raynor's Raiders",
  "relentless-leader": "Relentless Leader",
  "revolution-overdrive": "Revolution Overdrive",
  "scorched-earth": "Scorched Earth",
  "scouting-drone": "Scouting Drone",
  "steel-resolve": "Steel Resolve",
  "vampiric-assault": "Vampiric Assault",
  "arcane-barrier": "Arcane Barrier",
  "arcane-power": "Arcane Power",
  "backdraft": "Backdraft",
  "chain-bomb": "Chain Bomb",
  "clairvoyance": "Clairvoyance",
  "convection": "Convection",
  "energy-roil": "Energy Roil",
  "envenom": "Envenom",
  "fel-infusion": "Fel Invusion",
  "fission-bomb": "Fission Bomb",
  "flamethrower": "Flamethrower",
  "fury-of-the-sunwell": "Fury of the Sunwell",
  "gathering-power": "Gathering Power",
  "gravity-throw": "Gravity Throw",
  "mana-addict": "Mana Addict",
  "mana-tap": "Mana Tap",
  "nether-wind": "Nether Wind",
  "phoenix": "Phoenix",
  "presence-of-mind": "Presence of Mind",
  "pyroblast": "Pyroblast",
  "pyromaniac": "Pyrmaniac",
  "rebirth": "Rebirth",
  "sunfire-enchantment": "Sunfire Enchantment",
  "tri-optimal": "Tri-Optimal",
  "arcane-intellect": "Arcane Intellect",
  "cold-snap": "Cold Snap",
  "conjurer-s-pursuit": "Conjurer's Pursuit",
  "deep-chill": "Deep Chill",
  "frost-armor": "Frost Armor",
  "frostbitten": "Frostbitten",
  "frost-shards": "Frost Shards",
  "ice-barrier": "Ice Barrier",
  "ice-floes": "Ice Floes",
  "ice-lance": "Ice Lance",
  "icy-veins": "Icy Veins",
  "improved-ice-block": "Improved Ice Block",
  "lingering-chill": "Lingering Chill",
  "northern-exposure": "Northern Exposure",
  "numbing-blast": "Numbing Blast",
  "ring-of-frost": "Ring of Frost",
  "snow-crash": "Snow Crash",
  "snowstorm": "Snowstorm",
  "storm-front": "Storm Front",
  "summon-water-elemental": "Summon Water Elemental",
  "wintermute": "Wintermute",
  "winter-s-reach": "Winter's Reach",
  "avatar": "Avatar",
  "battle-momentum": "Battle Momentum",
  "crowd-control": "Crowd Control",
  "dwarf-launch": "Dwarf Launch",
  "give-em-the-axe": "Give'em the Axe!",
  "grand-slam": "Grand Slam",
  "haymaker": "Haymaker",
  "healing-static": "Healing Static",
  "heavy-impact": "Heavy Impact",
  "infused-hammer": "Infused Hammer",
  "landing-momentum": "Landing Momentum",
  "perfect-storm": "Perfect Storm",
  "piercing-bolt": "Piercing Bolt",
  "reverberation": "Reverberation",
  "skullcracker": "Skullcracker",
  "sledgehammer": "Sledgehammer",
  "stoneform": "Stoneform",
  "third-wind": "Third Wind",
  "thunder-burn": "Thunder Burn",
  "thunder-strike": "Thunder Strike",
  "unstoppable-force": "Unstoppable Force",
  "celestial-attunement": "Celestial Attunement",
  "celestial-wrath": "Celestial Wrath",
  "empower": "Empower",
  "healing-ward": "Healing Ward",
  "hunter-s-swiftness": "Hunter's Swiftness",
  "huntress-fury": "Huntress' Fury",
  "lunar-blaze": "Lunar Blaze",
  "mark-of-mending": "Mark of Mending",
  "overflowing-light": "Overflowing Light",
  "pierce": "Pierce",
  "protective-shield": "Protective Shield",
  "quickening-blessing": "Quickening Blessing",
  "ranger": "Ranger",
  "ranger-s-mark": "Ranger's Mark",
  "searing-arrows": "Searing Arrows",
  "shadowstalk": "Shadowstalk",
  "shooting-star": "Shooting Star",
  "shrink-ray": "Shrink Ray",
  "sprint": "Sprint",
  "starfall": "Starfall",
  "trueshot-aura": "Trueshot Aura",
  "baneling-massacre": "Baneling Massacre",
  "bile-drop": "Bile Drop",
  "brood-expansion": "Brood Expansion",
  "broodling-nest": "Broodling Nest",
  "centrifugal-hooks": "Centrifugal Hooks",
  "corpse-feeders": "Corpse Feeders",
  "demolitionist": "Demolitionist",
  "devouring-maw": "Devouring Maw",
  "endless-creep": "Endless Creep",
  "envenomed-spines": "Envenomed Spines",
  "fury-of-the-storm": "Fury of the Storm",
  "grooved-spines": "Grooved Spines",
  "medusa-blades": "Medusa Blades",
  "metabolic-boost": "Metabolic Boost",
  "nydus-network": "Nydus Network",
  "rapid-incubation": "Rapid Incubation",
  "reconstitution": "Reconstitution",
  "tumor-clutch": "Tumor Clutch",
  "tyrant-maw": "Tyrant Maw",
  "ventral-sacs": "Ventral Sacs",
  "volatile-acid": "Volatile Acid",
  "infest": "Infest",
  "mutalisk": "Mutalisk",
  "apocalypse": "Apocalypse",
  "continuous-overpower": "Continuous Overpower",
  "demonic-strength": "Demonic Strength",
  "devastating-charge": "Devastating Charge",
  "devil-s-due": "Devil's Due",
  "domination": "Domination",
  "dying-breath": "Dying Breath",
  "essence-of-the-slain": "Essence of the Slain",
  "fire-devil": "Fire Devil",
  "firestorm": "Firestorm",
  "from-the-shadows": "From the Shadows",
  "hellstorm": "Hellstorm",
  "life-leech": "Life Leech",
  "lightning-breath": "Lightning Breath",
  "lord-of-terror": "Lord of Terror",
  "overwhelming-force": "Overwhelming Force",
  "rampage": "Rampage",
  "siphon-the-dead": "Siphon the Dead",
  "soul-catcher": "Soul Catcher",
  "soul-feast": "Soul Feast",
  "soul-steal": "Soul Steal",
  "arsenal": "Arsenal",
  "caltrops": "Caltrops",
  "composite-arrows": "Composite Arrows",
  "cost-effective-materials": "Cost-Effective Materials",
  "frost-shot": "Frost Shot",
  "hot-pursuit": "Hot Pursuit",
  "manticore": "Manticore",
  "puncturing-arrow": "Puncturing Arrow",
  "punishment": "Punishment",
  "rain-of-vengeance": "Rain of Vengeance",
  "rancor": "Rancor",
  "repeating-arrow": "Repeating Arrow",
  "searing-attacks": "searing-attacks",
  "siphoning-arrow": "siphoning-arrow",
  "storm-of-vengeance": "Storm of Vengeance",
  "strafe": "Strafe",
  "tempered-by-discipline": "Tempered by Discipline",
  "tumble": "Tumble",
  "vengeance": "Vengeance",
  "advanced-block": "Advanced Block",
  "bioshield": "Bioshield",
  "caduceus-reactor-2-0": "Caduceus Reactor 2.0",
  "clear": "Clear",
  "couples-therapy": "Couples Therapy",
  "feedback-loop": "Feedback Loop",
  "infused-grenade": "Infused Grenade",
  "inoculation": "Inoculation",
  "intensive-care": "Intensive Care",
  "irradiate": "Irradiate",
  "medbay": "Medbay",
  "medivac-dropship": "Medivac Dropship",
  "preventative-care": "Preventative Care",
  "prolonged-safeguard": "Prolonged Safeguard",
  "second-opinion": "Second Opinion",
  "shield-sequencer": "Shield Sequencer",
  "stim-drone": "Stim Drone",
  "system-shock": "System Shock",
  "transfusion": "Transfusion",
  "trauma-trigger": "Trauma Trigger",
  "upgraded-ballistics": "Upgraded Ballistics",
  "crowd-pleaser": "Crowd Pleaser",
  "death-metal": "Death Metal",
  "double-necked-guitar": "Double-Necked Guitar",
  "echo-pedal": "Echo Pedal",
  "encore": "Encore",
  "face-smelt": "Face Smelt",
  "groupies": "Groupies",
  "guitar-hero": "Guitar Hero",
  "hammer-on": "Hammer On",
  "just-keep-rockin": "Just Keep Rockin'",
  "loud-speakers": "Loud Speakers",
  "mic-check": "Mic Check",
  "mosh-pit": "Mosh Pit",
  "pinball-wizard": "Pinball Wizard",
  "prog-rock": "Prog Rock",
  "pwn-shop-guitar": "Pwn Shop Guitar",
  "rolling-like-a-stone": "Rolling Like a Stone",
  "show-stopper": "Show Stopper",
  "speed-metal": "Speed Metal",
  "stage-dive": "Stage Dive",
  "tour-bus": "Tour Bus",
  "amplified-healing": "Amplified Healing",
  "benediction": "Benediction",
  "blessed-champion": "Blessed Champion",
  "boundless-conviction": "Boundless Conviction",
  "bulwark-of-light": "Bulwark of Light",
  "burden-of-guilt": "Burden of Guilt",
  "divine-hurricane": "Divine Hurricane",
  "divine-shield": "Divine Shield",
  "divine-storm": "Divine Storm",
  "fist-of-justice": "Fist of Justice",
  "gathering-radiance": "Gathering Radiance",
  "hammer-of-the-lightbringer": "Hammer of the Lightbringer",
  "holy-fire": "Holy Fire",
  "holy-shock": "Holy Shock",
  "reach": "Reach",
  "redemption": "Redemption",
  "wave-of-light": "Wave of Light",
  "double-dragon": "Double Dragon",
  "elusive-feet": "Elusive Feet",
  "gale-force": "Gale Force",
  "herbal-cleanse": "Herbal Cleanse",
  "hindering-winds": "Hindering Winds",
  "jug-of-1-000-000-cups": "Jug of 1,000,000 Cups",
  "jug-of-1-000-cups": "Jug of 1,000 Cups",
  "kung-fu-hustle": "Kung Fu Hustle",
  "lightning-serpent": "Lightning Serpent",
  "lingering-blind": "Lingering Blind",
  "mass-vortex": "Mass Vortex",
  "mending-serpent": "Mending Serpent",
  "pitch-perfect": "Pitch Perfect",
  "pro-toss": "Pro Toss",
  "safety-sprint": "Safety Sprint",
  "serpent-sidekick": "Serpent Sidekick",
  "shake-it-off": "Shake it Off",
  "surging-winds": "Surging Winds",
  "the-good-stuff": "The Good Stuff",
  "timeless-creature": "Timeless Creature",
  "two-for-one": "Two for One",
  "water-dragon": "Water Dragon",
  
  "advanced-cloaking": "Advanced Cloaking",
  "ambush-snipe": "Ambush Snipe",
  "anti-armor-shells": "Anti-Armor Shells",
  "covert-ops": "Covert-Ops",
  "crippling-shot": "Crippling Shot",
  "double-fake": "Double Fake",
  "explosive-round": "Explosive Round",
  "fast-reload": "Fast Reload",
  "headshot": "Headshot",
  "lethal-decoy": "Lethal Decoy",
  "one-in-the-chamber": "One in the Chamber",
  "overdrive": "Overdrive",
  "perfect-shot": "Perfect Shot",
  "precision-barrage": "Precision Barrage",
  "precision-strike": "Precision Strike",
  "psi-op-rangefinder": "Psi-Op Rangefinder",
  "railgun": "Railgun",
  "remote-delivery": "Remote Delivery",
  "tazer-rounds": "Tazer Rounds",
  "triple-tap": "Triple Tap",
  "double-tap": "Double Tap",
  "ghost-protocol": "Ghost Protocol",
  "holo-stability": "Holo Stability",
  "longshot": "Longshot",
  "psionic-efficiency": "Psionic Efficiency",
  "rapid-projection": "Rapid Projection",
  "snipe-master": "Snipe Master",
  "tactical-espionage": "Tactical Espionage",
  "blessed-hammer": "Blessed Hammer",
  "blessed-shield": "Blessed Shield",
  "conviction": "Conviction",
  "eternal-retaliation": "Eternal Retaliation",
  "falling-sword": "Falling Sword",
  "fanaticism": "Fanaticism",
  "heaven-s-fury": "Heaven's Fury",
  "hold-your-ground": "Hold Your Ground",
  "holy-renewal": "Holy Renewal",
  "indestructible": "Indestructible",
  "knight-takes-pawn": "Knight Takes Pawn",
  "laws-of-hope": "Laws of Hope",
  "radiating-faith": "Radiating Faith",
  "reinforce": "Reinforce",
  "righteous-smash": "Righteous Smash",
  "roar": "Roar",
  "sins-exposed": "Sins Exposed",
  "subdue": "Subdue",
  "the-crusade-marches-on": "The Crusade Marches On",
  "earthen-shields": "Earthen Shields",
  "earthquake": "Earthquake",
  "forked-lightning": "Forked Lightning",
  "frostwolf-s-grace": "Frostwolf's Grace",
  "grace-of-air": "Grace of Air",
  "mana-tide": "Mana Tide",
  "rabid-wolves": "Rabid Wolves",
  "restless-wolves": "Restless Wolves",
  "ride-the-lightning": "Ride the Lightning",
  "ride-the-wind": "Ride the Wind",
  "rolling-thunder": "Rolling Thunder",
  "spirit-journey": "Spirit Journey",
  "stone-wolves": "Stone Wolves",
  "sundering": "Sundering",
  "tempest-fury": "Tempest Fury",
  "wind-shear": "Wind Shear",
  "worldbreaker": "Worldbreaker",
  "aftershock": "Aftershock",
  "anger-management": "Anger Management",
  "arreat-crater": "Arreat Crater",
  "composite-spear": "Composite Spear",
  "endless-fury": "Endless Fury",
  "ferocious-healing": "Ferocious Healing",
  "furious-blow": "Furious Blow",
  "hurricane": "Hurricane",
  "ignore-pain": "Ignore Pain",
  "leap": "Leap",
  "life-funnel": "Life Funnel",
  "mystical-spear": "Mystical Spear",
  "nerves-of-steel": "Nerves of Steel",
  "no-escape": "No Escape",
  "poisoned-spear": "Poisoned Spear",
  "shattered-ground": "Shattered Ground",
  "shot-of-fury": "Shot od Fury",
  "war-paint": "War Paint",
  "wrath-of-the-berserker": "Wrath of the Berserker",
  "barbed-shot": "Barbed Shot",
  "cold-embrace": "Cold Embrace",
  "corruption": "Corruption",
  "dark-lady-s-call": "Dark Lady's Call",
  "deafening-blast": "Deafening Blast",
  "evasive-fire": "Evasive Fire",
  "life-drain": "Life Drain",
  "lost-soul": "Lost Soul",
  "overflowing-quiver": "Overflowing Quiver",
  "overwhelming-affliction": "Overwhelming Affliction",
  "paralysis": "Paralysis",
  "possession": "Possession",
  "ranger-s-ambush": "Ranger's Ambush",
  "remorseless": "Remorseless",
  "shade-form": "Shade Form",
  "splinter-shot": "Splinter Shot",
  "unstable-poison": "Unstable Poison",
  "wailing-arrow": "Wailing Arrow",
  "will-of-the-forsaken": "Will of the Forsaken",
  "windrunner": "Windrunner",
  "with-the-wind": "With the Wind",
  "blazing-fists": "Blazing Fists",
  "blinding-speed": "Blinding Speed",
  "circle-of-life": "Circle of Life",
  "divine-palm": "Divine Palm",
  "echo-of-heaven": "Echo of Heaven",
  "epiphany": "Epiphany",
  "fists-of-fury": "Fists of Fury",
  "foresight": "Foresight",
  "insight": "Insight",
  "iron-fists": "Iron Fists",
  "overtake": "Overtake",
  "peaceful-repose": "Peaceful Repose",
  "quicksilver": "Quicksilver",
  "seven-sided-strike": "Seven-Sided Strike",
  "soothing-breeze": "Soothing Breeze",
  "transcendence": "Transcendence",
  "transgression": "Transgression",
  "way-of-the-hundred-fists": "Way of the Hundred Fists",
  "annihilating-spirit": "Annihilating Spirit",
  "blood-ritual": "Blood Ritual",
  "dead-rush": "Dead Rush",
  "death-ritual": "Death Ritual",
  "fresh-corpses": "Fresh Corpses",
  "gargantuan": "Gargantuan",
  "gidbinn": "Gidbinn",
  "humongoid": "Humongoid",
  "infested-toads": "Infested Toads",
  "leaping-spiders": "Leaping Spiders",
  "promote": "Promote",
  "ravenous-spirit": "Ravenous Spirit",
  "specialized-toxin": "Specialized Toxin",
  "spider-cluster": "Spider Cluster",
  "thing-of-the-deep": "Thing of the Deep",
  "toad-affinity": "Toad Affinity",
  "toads-of-hugeness": "Toads of Hugeness",
  "aerie-gusts": "Aerie Gusts",
  "afterburner": "Afterburner",
  "boomerang": "BOOMerang",
  "call-of-the-wildhammer": "Call of the Wildhammer",
  "charged-up": "Charged Up",
  "crippling-hammer": "Crippling Hammer",
  "epic-mount": "Epic Mount",
  "first-aid": "First Aid",
  "flow-rider": "Flow Rider",
  "free-roll": "Free Roll",
  "gathering-storm": "Gathering Storm",
  "hammer-time": "Hammer Time",
  "hinterland-blast": "Hinterland Blast",
  "mighty-gust": "Mighty Gust",
  "power-throw": "Power Throw",
  "secret-weapon": "Secret Weapon",
  "static-shield": "Static SHield",
  "thunderstrikes": "Thunderstrikes",
  "updraft": "Updraft",
  "wind-tunnel": "Wind Tunnel",
  "elune-s-grace": "Elune's Grace",
  "enduring-growth": "Enduring Growth",
  "full-moonfire": "Full Moonfire",
  "harmony": "Harmony",
  "hindering-moonfire": "Hindering Moonfire",
  "life-seed": "Life Seed",
  "lunar-shower": "Lunar Shower",
  "moonburn": "Moonburn",
  "nightmare": "Nightmare",
  "rampant-growth": "Rampant Growth",
  "serenity": "Serenity",
  "shan-do-s-clarity": "Shan'do's Clarity",
  "strangling-vines": "Strangling Vines",
  "tenacious-roots": "Tenacious Roots",
  "tranquility": "Tranquility",
  "twilight-dream": "Twilight Dream",
  "vengeful-roots": "Vengeful Roots",
  "versatile": "Versatile",
  "buried-alive": "Buried Alive",
  "consume-vitality": "Consume Vitality",
  "crushing-hope": "Crushing Hope",
  "death-march": "Death March",
  "drain-momentum": "Drain Momentum",
  "entomb": "Entomb",
  "fealty-unto-death": "Fealty Unto Death",
  "ghastly-reach": "Ghastly Reach",
  "hardened-bones": "Hardened Bones",
  "hopelessness": "Hopelessness",
  "lingering-apparition": "Lingering Apparition",
  "mana-thirst": "Mana Thirst",
  "march-of-the-black-king": "March of the Black King",
  "ossein-renewal": "Ossein Renewal",
  "paralyzing-rage": "Paralyzing Rage",
  "reanimation": "Reanimation",
  "renewed-swing": "Renewed Swing",
  "royal-focus": "Royal Focus",
  "spectral-leech": "Spectral Leech",
  "unyielding-despair": "Unyielding Despair",
  "willing-vessel": "Willing Vessel",
  "assassin-s-blade": "Assassin's Blade",
  "double-bombs": "Double Bombs",
  "greater-cleave": "Greater Cleave",
  "master-warp-blade": "Master Warp-Blade",
  "nerazim-fury": "Nerazim Fury",
  "protective-prison": "Protective Prison",
  "rapid-displacement": "Rapid Displacement",
  "rending-cleave": "Rending Cleave",
  "shadow-assault": "Shadow Assault",
  "shadow-spike": "Shadow Spike",
  "sustained-anomaly": "Sustained Anomaly",
  "vampiric-strike": "Vampiric Strike",
  "void-prison": "Void Prison",
  "void-slash": "Void Slash",
  "vorpal-blade": "Vorpal Blade",
  "wormhole": "Wormhole",
  "advanced-artillery": "Advanced Artillery",
  "advanced-lava-strike": "Advanced Lava Strike",
  "ambush": "Ambush",
  "barricade": "Barricade",
  "blunt-force-gun": "Blunt Force Gun",
  "bullhead-mines": "Bullhead Mines",
  "excessive-force": "Excessive Force",
  "first-strike": "First Strike",
  "graduating-range": "Graduating Range",
  "hover-siege-mode": "Hover Siege Mode",
  "hyper-cooling-engines": "Hyper-Cooling Engines",
  "lethal-blast": "Lethal Blast",
  "maelstrom-shells": "Maelstrom Shells",
  "mine-field": "Mine Field",
  "napalm-strike": "Napalm Strike",
  "orbital-bfg": "Orbital BFG",
  "resistant": "Resistant",
  "slowing-mines": "Slowing Mines",
  "armor-piercing-rounds": "Armor Piercing Rounds",
  "big-red-button": "Big Red Button",
  "commandeer-odin": "Commandeer Odin",
  "concussion-grenade": "Consussion Grenade",
  "dash": "Dash",
  "drakken-laser-drill": "Drakken Laser Drill",
  "focusing-diodes": "Focusing Diodes",
  "lead-rain": "Lead Rain",
  "lock-and-load": "Lock and Load",
  "melting-point": "Melting Point",
  "quarterback": "Quarterback",
  "rapid-fire": "Rapid Fire",
  "shredder-grenade": "Shredder Grenade",
  "sizzlin-attacks": "Sizzlin' Attacks",
  "spray-n-pray": "Spray 'n' Pray",
  "stim-pack": "Stim Pack",
  "problem-solver": "Problem Solver",
  "ancestral-healing": "Ancestral Healing",
  "bloodlust": "Bloodlust",
  "chain-reaction": "Chain Reaction",
  "colossal-totem": "Colossal Totem",
  "earthgrasp-totem": "Earthgrasp Totem",
  "earth-shield": "Earth Shield",
  "empowering-charge": "Empowering Charge",
  "farseer-s-blessing": "Farseer's Blessing",
  "farsight": "Farsight",
  "feral-heart": "Feral Heart",
  "feral-lunge": "Feral Lunge",
  "gladiator-s-war-shout": "Gladiator's War Shout",
  "healing-surge": "Healing Surge",
  "healing-totem": "Healing Totem",
  "lightning-bond": "Lightning Bond",
  "reactive-spark": "Reactive Spark",
  "shadow-wolf": "Shadow Wolf",
  "spiritwalker-s-grace": "Spiritwalker's Grace",
  "stormcaller": "Stormcaller",
  "tidal-waves": "Tidal Waves",
  "forward-momentum": "Forward Momentum",
  "blood-and-thunder": "Blood and Thunder",
  "earthliving-enchant": "Earthliving Enchant",
  "electric-charge": "Electric Charge",
  "hunger-of-the-wolf": "Hunger of the Wolf",
  "rising-storm": "Rising Storm",
  "totemic-projection": "Totemic Projection",
  "wolf-run": "Wolf Run",
  "abattoir": "Abattoir",
  "blood-frenzy": "Blood Frenzy",
  "brutal-strike": "Brutal Strike",
  "cheap-shot": "Cheap Shot",
  "chop-meat": "Chop Meat",
  "crave-flesh": "Crave Flesh",
  "crippling-slam": "Crippling Slam",
  "enraged": "Enraged",
  "final-assault": "Final Assault",
  "fires-of-hell": "Fires of Hell",
  "flail-axe": "Flail Axe",
  "furnace-blast": "Furnace Blast",
  "insatiable-blade": "Insatiable Blade",
  "invigoration": "Invigoration",
  "lamb-to-the-slaughter": "Lamb to the Slaughter",
  "savage-charge": "Savage Charge",
  "slaughterhouse": "Slaughterhouse",
  "unrelenting-pursuit": "Unrelenting Pursuit",
  "victuals": "Victuals",
  "archon": "Archon",
  "deep-shift": "Deep Shift",
  "dimensional-warp": "Dimensional Warp",
  "distortion-beam": "Distortion Beam",
  "evasive-shielding": "Evasive Shielding",
  "force-barrier": "Force Barrier",
  "force-wall": "Force Wall",
  "khala-s-embrace": "Khala's Embrace",
  "leeching-plasma": "Leeching Plasma",
  "mental-acuity": "Mental Acuity",
  "overload": "Overload",
  "prescience": "Prescience",
  "psi-infusion": "Psi-Infusion",
  "reinforce-structure": "Reinforce Structure",
  "resonation": "Resonation",
  "scryer": "Scryer",
  "second-strike": "Second Strike",
  "static-charge": "Static Charge",
  "twilight-archon": "Twilight Archon",
  "adaptation": "Adaptation",
  "aggressive-defense": "Aggressive Defense",
  "assimilation-mastery": "Assimilation Mastery",
  "blade-torrent": "Blade Torrent",
  "clean-kill": "Clean Kill",
  "double-strike": "Double Strike",
  "energizing-grasp": "Energizing Grasp",
  "essence-for-essence": "Essence for Essence",
  "eviscerate": "Eviscerate",
  "fury-of-the-swarm": "Fury of the Swarm",
  "impaling-swarm": "Impaling Swarm",
  "lingering-essence": "Lingering Essence",
  "maelstrom": "Maelstrom",
  "omegastorm": "Omegastorm",
  "psionic-pulse": "Psionic Pulse",
  "queen-s-rush": "Queen's Rush",
  "sharpened-blades": "Sharpened Blades",
  "siphoning-impact": "Siphoning Impact",
  "summon-ultralisk": "Summon Ultralisk",
  "torrasque": "Torrasque",
  "angelic-absorption": "Angelic Absorption",
  "angelic-might": "Angelic Might",
  "angel-of-justice": "Angel of Justice",
  "angel-s-grace": "Angel's Grace",
  "blade-of-justice": "Blade of Justice",
  "even-in-death": "Even in Death",
  "holy-arena": "Holy Arena",
  "holy-ground": "Holy Ground",
  "horadric-reforging": "Horadric Reforging",
  "imposing-will": "Imposing Will",
  "judgment": "Judgment",
  "protection-in-death": "Protection in Death",
  "purge-evil": "Purge Evil",
  "reciprocate": "Reciprocate",
  "retribution": "Retribution",
  "salvation": "Salvation",
  "sanctification": "Sanctification",
  "zealotry": "Zealotry",
  "chew-your-food": "Chew Your Food",
  "dampen-magic": "Dampen Magic",
  "fishing-hook": "Fishing Hook",
  "gorge": "Gorge",
  "heavy-slam": "Heavy Slam",
  "helping-hand": "Helping Hand",
  "hungry-for-more": "Hungry for More",
  "hungry-hungry-stitches": "Hungry Hungry Stitches",
  "indigestion": "Indigestion",
  "last-bite": "Last Bite",
  "mega-smash": "Mega Smash",
  "pulverize": "Pulverize",
  "putrid-bile": "Putrid Bile",
  "putrid-ground": "Putrid Ground",
  "regenerative-bile": "Regenarative Bile",
  "savor-the-flavor": "Savor the Flavor",
  "shish-kabob": "Shish Kabob",
  "tenderizer": "Tenderizer",
  "toxic-gas": "Toxic Gas",
  "vile-cleaver": "Vile Cleaver",
  "battered-assault": "Battered Assault",
  "demonic-form": "Demonic Form",
  "fel-reach": "Fel Reach",
  "friend-or-foe": "Friend or Foe",
  "hunter-s-onslaught": "Hunter's Onslaught",
  "immolation": "Immolation",
  "lunge": "Lunge",
  "marked-for-death": "Marked for Death",
  "metamorphosis": "Metamorphosis",
  "nowhere-to-hide": "Nowhere to Hide",
  "rapid-chase": "Rapid Chase",
  "reflexive-block": "Reflexive Block",
  "second-sweep": "Second Sweep",
  "shadow-shield": "Shadow Shield",
  "sixth-sense": "Sixth Sense",
  "the-hunt": "The Hunt",
  "thirsting-blade": "Thirsting Blade",
  "thrill-of-battle": "Thrill of Battle",
  "unbound": "Unbound",
  "and-a-shark-too": "... And A Shark Too!",
  "assault-egg": "Assault Egg",
  "bigger-slime": "Bigger Slime",
  "bubble-breeze": "Bubble Breeze",
  "bubble-machine": "Bubble Machine",
  "compressed-air": "Compressed Air",
  "continuous-slime": "Continuous Slime",
  "hidden-assault": "Hidden Assault",
  "hindering-slime": "Hindering Slime",
  "living-the-dream": "Living the Dream",
  "march-of-the-murlocs": "March of the Murlocs",
  "never-ending-murlocs": "Never-Ending Murlocs",
  "octo-grab": "Octo-Grab",
  "rejuvenating-bubble": "Rejuvenating Bubble",
  "slime-advantage": "Slime Advantage",
  "slimy-end": "Slimy End",
  "slimy-pufferfish": "Slimy Pufferfish",
  "tufferfish": "Tufferfish",
  "wrath-of-cod": "Wrath of Cod",
  "break-it-down": "Break it Down!",
  "clockwerk-steam-fists": "Clockwerk Steam Fists",
  "engine-gunk": "Engine Gunk",
  "extra-tnt": "Extra TNT",
  "ez-pz-dimensional-ripper": "EZ-PZ Dimensional Ripper",
  "goblin-fusion": "Goblin Fusion",
  "grav-o-bomb-3000": "Grav-O-Bomb 3000",
  "hyperfocus-coils": "Hyperfocus Coils",
  "kwik-release-charge": "Kwik Release Charge",
  "long-ranged-turrets": "Long-Ranged Turrets",
  "mecha-lord": "Mecha-Lord",
  "miniature-black-hole": "Miniature Black Hole",
  "reduce-reuse-recycle": "Reduce, Reuse, Recycle",
  "robo-goblin": "Robo-Goblin",
  "rock-it-turret-xl": "Rock-it! Turret XL",
  "scrap-o-matic-smelter": "Scrap-o-Matic Smelter",
  "turret-storage": "Turret Storage",
  "abolish-magic": "Abolish Magic",
  "blossom-swell": "Blossom Swell",
  "boundless-stride": "Boundless Stride",
  "choking-pollen": "Choking Pollen",
  "cruel-spores": "Cruel Spores",
  "dividing-wisp": "Dividing Wisp",
  "forest-s-wrath": "Forest's Wrath",
  "galloping-gait": "Galloping Gait",
  "greater-spell-shield": "Greater Spell Shield",
  "invigorating-spores": "Invigorating Spores",
  "leaping-strike": "Leaping Strike",
  "let-them-wither": "Let Them Wither",
  "natural-perspective": "Natural Perspective",
  "nature-s-culling": "Nature's Culling",
  "nimble-wisp": "Nimble Wisp",
  "pestering-blossom": "Pestering Blossom",
  "photosynthesis": "Photosynthesis",
  "siphoning-toxin": "Siphoning Toxin",
  "skybound-wisp": "Skybound Wisp",
  "splintered-spear": "Splintered Spear",
  "star-wood-spear": "Star Wood Spear",
  "thornwood-vine": "Thornwood Vine",
  "timelost-wisp": "Timelost Wisp",
  "unfair-advantage": "Unfair Advantage",
  "wild-vigor": "Wild Vigor",
  "a-touch-of-honey": "A Touch of Honey",
  "bolder-flavor": "Bolder Flavor",
  "bottomless-mug": "Bottomless Mug",
  "brewmaster-s-balance": "Brewmaster's Balance",
  "brew-strike": "Brew Strike",
  "combat-stance": "combat-stance",
  "combination-attack": "Combination Attack",
  "consuming-flame": "Consuming Flame",
  "deadly-strike": "Deadly Strike",
  "deep-breath": "Deep Breath",
  "elemental-conduit": "Elemental Conduit",
  "enough-to-share": "Enough to Share",
  "full-keg": "Full Keg",
  "grounding-brew": "Grounding Brew",
  "keg-toss": "Keg Toss",
  "pressure-point": "Pressure Point",
  "ring-of-fire": "Ring of Fire",
  "storm-earth-fire": "Storm, Earth, Fire",
  "swift-reflexes": "Swift Reflexes",
  "untapped-potential": "Untapped Potential",
  "wandering-keg": "Wandering Keg",
  "64-kb-marathon": "64 KB Marathon",
  "baleog-the-fierce": "Baleog the Fierce",
  "checkpoint-reached": "Checkpoint Reached",
  "erik-the-swift": "Erik the Swift",
  "explosive-attacks": "Explosive Attacks",
  "hunka-burning-olaf": "Hunka' Burning Olaf",
  "impatience-is-a-virtue": "Impatience is a Virtue",
  "it-s-a-sabotage": "It's a Sabotage!",
  "jump": "Jump!",
  "large-and-in-charge": "Large and in Charge",
  "longboat-raid": "Longboat Raid!",
  "nordic-attack-squad": "Nordic Attack Squad",
  "norse-force": "Norse Force!",
  "olaf-the-stout": "Olaf the Stout",
  "pain-don-t-hurt": "Pain Don't Hurt",
  "play-again": "Play Again!",
  "ragnarok-n-roll": "Ragnarok 'n' Roll!",
  "spin-to-win": "Spin to Win!",
  "spy-games": "Spy Games",
  "the-sequel": "The Sequel!",
  "viking-bribery": "Viking Bribery",
  "aspect-of-the-beast": "Aspect of the Beast",
  "aspect-of-the-hawk": "Aspect of the Hawk",
  "barkskin": "Barkskin",
  "bear-necessities": "Bear Necessities",
  "bestial-wrath": "Bestial Wrath",
  "bird-of-prey": "Bird of Prey",
  "blood-of-the-rhino": "Blood of the Rhino",
  "crippling-talons": "Crippling Talons",
  "critical-care": "Critical Care",
  "easy-prey": "Easy Prey",
  "feign-death": "Feign Death",
  "flare": "Flare",
  "frenzy-of-kalimdor": "Frenzy of Kalimdor",
  "grizzled-bear": "Grizzled Bear",
  "hardened-skin": "Hardened Skin",
  "hungry-bear": "Hungry Bear",
  "hunter-gatherer": "Hunter-Gatherer",
  "kill-command": "Kill Command",
  "primal-intimidation": "Primal Intimidation",
  "spirit-bond": "Spirit Bond",
  "survivalist-training": "Survivalist Training",
  "taking-flight": "Taking Flight",
  "thrill-of-the-hunt": "Thrill of the Hunt",
  "throwing-axes": "Throwing Axes",
  "unleash-the-boars": "Unleash the Boars",
  "wildfire-bear": "Wildfire Bear",
  "blazing-bulwark": "Blazing Bulwark",
  "crippling-blow": "Crippling Blow",
  "c-thun-s-gift": "C\'thun\'s Gift",
  "favor-of-the-old-gods": "Favor Of The Old Gods",
  "fire-eater": "Fire Eater",
  "frenzied-fists": "Frenzied Fists",
  "fuel-for-the-flame": "Fuel for the Flame",
  "hammer-of-twilight": "Hammer of Twilight",
  "i-am-hurrying": "I AM Hurrying!",
  "molten-block": "Molten Block",
  "power-surge": "Power Surge",
  "rollback": "Rollback",
  "runed-gauntlet": "Runed Gauntlet",
  "runic-feedback": "Runic Feedback",
  "seared-flesh": "Seared Flesh",
  "surge-of-stamina": "Surge of Stamina",
  "surging-dash": "Surging Dash",
  "the-will-of-gall": "The Will of Gall",
  "twilight-veil": "Twilight Veil",
  "upheaval": "Upheaval",
  "bomb-s-away": "Bomb's Away",
  "dark-descent": "Dark Descent",
  "double-back": "Double Back",
  "double-trouble": "Double Trouble",
  "dread-shield": "Dread Shield",
  "edge-of-madness": "Edge of Madness",
  "eye-of-kilrogg": "Eye of Kilrogg",
  "giant-scorcher": "Giant Scorcher",
  "psychotic-break": "Psychotic Break",
  "rising-dread": "Rising Dread",
  "shadow-bolt-volley": "Shadow Bolt Volley",
  "shadowflare": "Shadowflare",
  "shadowfury": "Shadowfury",
  "shove": "Shove",
  "siphoning-runes": "Siphoning Runes",
  "speed-of-twilight": "Speed of Twilight",
  "spurred-onward": "Spurred Onward",
  "the-nether-calls": "The Nether Calls",
  "twilight-nova": "Twilight Nova",
  "twisting-nether": "Twisting Nether",
  "alpha-killer": "Alpha Killer",
  "concentrated-blast": "Concentrated Blast",
  "draught-overflow": "Draught Overflow",
  "eyes-in-the-dark": "Eyes in the Dark",
  "gilnean-roulette": "Gilnean Roulette",
  "go-for-the-throat": "Go for the Throat",
  "hunter-s-blunderbuss": "Hunter's Blunderbuss",
  "incendiary-elixir": "Incendiary Elixir",
  "insatiable": "Insatiable",
  "marked-for-the-kill": "Marked for the Kill",
  "on-the-prowl": "On the Prowl",
  "perfect-aim": "Perfect Aim",
  "quicksilver-bullets": "Quicksilver Bullets",
  "relentless-predator": "Relentless Predator",
  "running-wild": "Running Wild",
  "scented-tincture": "Scented Tincture",
  "thick-skin": "Thick Skin",
  "tooth-and-claw": "Tooth and Claw",
  "unfettered-assault": "Unfettered Assault",
  "unleashed": "Unleashed",
  "viciousness": "Viciousness",
  "visceral-attacks": "Visceral Attacks",
  "wizened-duelist": "Wizened Duealist",
  "wolfheart": "Wolfheart",
  "aether-walker": "Aether Walker",
  "arcane-orbit": "Arcane Orbit",
  "archon-pure-power": "Archon: Pure Power",
  "astral-presence": "Astral Presence",
  "calamity": "Calamity",
  "cannoneer": "Cannoneer",
  "charged-blast": "Charged Blast",
  "diamond-skin": "Diamond Skin",
  "disintegrate": "Disintegrate",
  "dominance": "Dominance",
  "ess-of-johan": "Ess of Johan",
  "fireflies": "Fireflies",
  "force-armor": "Force Armor",
  "glass-cannon": "Glass Cannon",
  "illusionist": "Illusionist",
  "mirrorball": "Mirrorball",
  "power-hungry": "Power Hungry",
  "repulsion": "Repulsion",
  "seeker": "Seeker",
  "tal-rasha-s-elements": "Tal Rasha's Elements",
  "temporal-flux": "Temporal Flux",
  "triumvirate": "Triumvirate",
  "wave-of-force": "Wave of Force",
  "zei-s-vengeance": "Zei's Vengeance"
};