window.talentPics = [  
  { safestr: "pressurized-glands", displaystr: "Pressurized Glands"},
  { safestr: "survival-instincts", displaystr: "Survival Instincts"},
  { safestr: "regenerative-microbes", displaystr: "Regenerative Microbes"},
  { safestr: "envenomed-nest", displaystr: "Envenomed Nest"},
  { safestr: "prolific-dispersal", displaystr: "Prolific Dispersal"},
  { safestr: "ballistospores", displaystr: "Ballistospores"},
  { safestr: "sustained-carapace", displaystr: "Sustained Carapace"},
  { safestr: "adrenal-overload", displaystr: "Adrenal Overload"},
  { safestr: "needlespine", displaystr: "Needlespine"},
  { safestr: "vile-nest", displaystr: "Vile Nest"},
  { safestr: "networked-carapace", displaystr: "Networked Carapace"},
  { safestr: "calldown-mule", displaystr: "Calldown: MULE"},
  { safestr: "adrenaline-boost", displaystr: "Adrenaline Boost"},
  { safestr: "assault-strain", displaystr: "Assault Strain"},
  { safestr: "bombard-strain", displaystr: "Bombard Strain"},
  { safestr: "envenomed-spikes", displaystr: "Envenomed Spikes"},
  { safestr: "evolutionary-link", displaystr: "Evolutionary Link"},
  { safestr: "evolution-complete", displaystr: "Evolution Complete"},
  { safestr: "evolve-monstrosity", displaystr: "Evolve Monstrosity"},
  { safestr: "hivemind", displaystr: "Hivemind"},
  { safestr: "locust-brood", displaystr: "Locust Brood"},
  { safestr: "locust-nest", displaystr: "Locust Nest"},
  { safestr: "soma-transference", displaystr: "Soma Transference"},
  { safestr: "spatial-efficiency", displaystr: "Spatial Efficiency"},
  { safestr: "ultimate-evolution", displaystr: "Ultimate Evolution"},
  { safestr: "volatile-mutation", displaystr: "Voltaile Mutation"},
  { safestr: "assault-scarab", displaystr: "Assault Scarab"},
  { safestr: "bed-of-barbs", displaystr: "Bed of Barbs"},
  { safestr: "beetle-juiced", displaystr: "Beetle Juiced"},
  { safestr: "blood-for-blood", displaystr: "Blood for Blood"},
  { safestr: "burning-rage", displaystr: "Burning Rage"},
  { safestr: "chitinous-plating", displaystr: "Chitinous Plating"},
  { safestr: "cocoon", displaystr: "Cocoon"},
  { safestr: "cryptweave", displaystr: "Cryptweave"},
  { safestr: "epicenter", displaystr: "Epicenter"},
  { safestr: "extended-spikes", displaystr: "Extended Spikes"},
  { safestr: "hardened-shield", displaystr: "Hardened Shield"},
  { safestr: "hive-master", displaystr: "Hive Master"},
  { safestr: "imposing-presence", displaystr: "Imposing Presence"},
  { safestr: "leeching-scarabs", displaystr: "Leeching Scarabs"},
  { safestr: "legion-of-beetles", displaystr: "Legion of Beetles"},
  { safestr: "locust-needles", displaystr: "Locust Needles"},
  { safestr: "locust-swarm", displaystr: "Locust Swarm"},
  { safestr: "mercenary-lord", displaystr: "Mercenary Lord"},
  { safestr: "persistent-carapace", displaystr: "Persistent Carapace"},
  { safestr: "regeneration-master", displaystr: "Regeneration Master"},
  { safestr: "rewind", displaystr: "Rewind"},
  { safestr: "shed-exoskeleton", displaystr: "Shed Exoskeleton"},
  { safestr: "spell-shield", displaystr: "Spell Shield"},
  { safestr: "symbiotic-armor", displaystr: "Symbiotic Armor"},
  { safestr: "underking", displaystr: "Underking"},
  { safestr: "urticating-spines", displaystr: "Urticating Spines"},
  { safestr: "amateur-opponent", displaystr: "Amateur Opponent"},
  { safestr: "chrono-surge", displaystr: "Chrono Surge"},
  { safestr: "follow-through", displaystr: "Follow Through"},
  { safestr: "graviton-vortex", displaystr: "Graviton Vortex"},
  { safestr: "khaydarian-resonance", displaystr: "Khaydarian Resonance"},
  { safestr: "lethal-alacrity", displaystr: "Lethal Alacrity"},
  { safestr: "nexus-blades", displaystr: "Nexus Blades"},
  { safestr: "orbital-bombardment", displaystr: "Orbital Bombardment"},
  { safestr: "phase-bulwark", displaystr: "Phase Bulwark"},
  { safestr: "psionic-synergy", displaystr: "Psionic Synergy"},
  { safestr: "psionic-wound", displaystr: "Psionic Wound"},
  { safestr: "purifier-beam", displaystr: "Purifier Beam"},
  { safestr: "reactive-parry", displaystr: "Reactive Parry"},
  { safestr: "seasoned-marksman", displaystr: "Seasoned Marksman"},
  { safestr: "shield-battery", displaystr: "Shield Battery"},
  { safestr: "shield-surge", displaystr: "Shield Surge"},
  { safestr: "solarite-reaper", displaystr: "Solarite Reaper"},
  { safestr: "suppression-pulse", displaystr: "Suppression Pulse"},
  { safestr: "target-purified", displaystr: "Target Purified"},
  { safestr: "templar-s-zeal", displaystr: "Templar's Zeal"},
  { safestr: "titan-killer", displaystr: "Titan Killer"},
  { safestr: "triple-strike", displaystr: "Triple Strike"},
  { safestr: "warp-sickness", displaystr: "Warp Sickness"},
  { safestr: "zealot-charge", displaystr: "Zealot Charge"},
  { safestr: "force-of-will", displaystr: "Force of Will"},
  { safestr: "absolute-zero", displaystr: "Absolute Zero"},
  { safestr: "army-of-the-dead", displaystr: "Army of the Dead"},
  { safestr: "biting-cold", displaystr: "Biting Cold"},
  { safestr: "block", displaystr: "Block"},
  { safestr: "death-touch", displaystr: "Death Touch"},
  { safestr: "destruction", displaystr: "Desctruction"},
  { safestr: "embrace-death", displaystr: "Embrace Death"},
  { safestr: "eternal-hunger", displaystr: "Eternal Hunger"},
  { safestr: "frostmourne-feeds", displaystr: "Frostmourne Feeds"},
  { safestr: "frost-presence", displaystr: "Frost Presence"},
  { safestr: "frost-strike", displaystr: "Frost Strike"},
  { safestr: "frozen-wastes", displaystr: "Frozen Wastes"},
  { safestr: "immortal-coil", displaystr: "Immortal Coil"},
  { safestr: "legion-of-northrend", displaystr: "Legion of Northrend"},
  { safestr: "obliterate", displaystr: "Obliterate"},
  { safestr: "relentless", displaystr: "Relentless"},
  { safestr: "rune-tap", displaystr: "Rune Tap"},
  { safestr: "stoneskin", displaystr: "Stoneskin"},
  { safestr: "summon-sindragosa", displaystr: "Summon Sindragosa"},
  { safestr: "trail-of-frost", displaystr: "Trail of Frost"},
  { safestr: "army-of-hell", displaystr: "Army of Hell"},
  { safestr: "battleborn", displaystr: "Battleborn"},
  { safestr: "black-pool", displaystr: "Black Pool"},
  { safestr: "bolt-of-the-storm", displaystr: "Bolt of the Storm"},
  { safestr: "bound-minion", displaystr: "Bound Minion"},
  { safestr: "bribe", displaystr: "Bribe"},
  { safestr: "demonic-invasion", displaystr: "Demonic Invasion"},
  { safestr: "demonic-smite", displaystr: "Demonic-Smite"},
  { safestr: "fifth-circle", displaystr: "Fifth Circle"},
  { safestr: "forced-recruitment", displaystr: "Forced Recruitment"},
  { safestr: "gluttonous-ward", displaystr: "Gluttonous Ward"},
  { safestr: "gluttony", displaystr: "Gluttony"},
  { safestr: "hedonism", displaystr: "Hedonism"},
  { safestr: "hellforged-armor", displaystr: "Hellforged Armor"},
  { safestr: "infernal-globe", displaystr: "Infernal Globe"},
  { safestr: "infused-power", displaystr: "Infused Power"},
  { safestr: "march-of-sin", displaystr: "March of Sin"},
  { safestr: "master-of-destruction", displaystr: "Master of Desctruction"},
  { safestr: "perishing-flame", displaystr: "Perishing Flame"},
  { safestr: "sieging-wrath", displaystr: "Sieging Wrath"},
  { safestr: "sin-s-grasp", displaystr: "Sin's Grasp"},
  { safestr: "taste-for-blood", displaystr: "Taste for Blood"}
  
];